spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@cluster0.tiaqv.mongodb.net/?retryWrites=true&w=majority/zuello-database
      database: zuello-database
      username: admin
      password: admin


